### ISSUE TITLE
204 responses are not handled correctly

### ISSUE THREAD

**Issue by chalenge** [octokit/plugin-paginate-rest.js#158]
`GET /repos/{owner}/{repo}/contributors` returns `204 No Content` when the repository is empty, i.e. with no commits. Trying to use paginate results in error 
```sh
TypeError: Cannot use 'in' operator to search for 'total_count' in undefined
```
Fun stuff:  `GET /repos/{owner}/{repo}/commits` returns `409 Conflict` which kinda matches the documentation here: https://developer.github.com/v3/git/

Maybe provide a workaround to this?

**Comment by gr2m** [comment]
Great catch! Yes, I think we should handle the case if a reponse is a 204. I think the `409` should already be handled correctly by throwing an error?

Would you like to send a pull request? I'd start out by creating a failing test

**Comment by chalenge** [comment]
@gr2m Yeah, I can push one. Let me get on it

**Comment by KianBadie** [comment]
I had to do some digging since too many people did not seem to have this issue. Glad to find the **exact** questions I had discussed here. And recent! 

I was confused why using the `paginate` method on `repos.listCommits` seemed to return an HTTP error and returned the mentioned `TypeError` on `repos.listContributors`. But it's reassuring to know it's being discussed.

I currently want to use paginate and catch the error when using `.paginate(octokit.repos.listContributors, ...)`  only for when the repository is empty (which I believe is what status code `204` is reserved for?). I was thinking of catching the error and seeing if the name of the error was `TypeError` and the message was `Cannot use 'in' operator to search for 'total_count' in undefined`. But I was unsure if this error would only happen for empty repos described by status code `204`, or if it would happen for other errors, which would result in me handling errors I did not want to handle. 

Is it possible for paginate to throw `TypeError: Cannot use 'in' operator to search for 'total_count' in undefined` in any other situations when using paginate on `octokit.repos.listCommits`?

Sorry if this isn't the place to ask, I just didn't see anywhere else online where someone else had this issue!

**Comment by gr2m** [comment]
Thanks Kia! The problem is that we do not account for a `204` response at this point. But we should, and resolve with an empty array in that case instead of trying to read the `total_count` property from a non-existing response body.

@chalenge are you still working on it?

**Comment by chalenge** [comment]
@gr2m Yeah, still on it. I been tied up with other things. I will push a fix for it over the weekend.

**Comment by KianBadie** [comment]
@gr2m @chalenge Thank you for your work and your responses. I have another related question: it was mentioned earlier, but is the HTTP Error with `409 Conflict` that is returned when using `paginate(octokit.repos.listCommits)` intentional as well?

**Comment by gr2m** [comment]
Not intentional, and I agree it would rather be a cause of confusion. Maybe we should catch the `409` error and also resolve with an empty array?

**Comment by gr2m** [comment]
@chalenge did you have a chance to finish the work on this, or would you like to? No pressure, just checking in

**Comment by Lorena-babygirl** [comment]
delete project JS #316
